[package]
name = "homer"
version = "0.1.0"
authors = ["Paul Mucur <mudge@mudge.name>"]
edition = "2018"

[dependencies]
reqwest = "0.9"
clap = "2.32"
openssl = { version = "0.10", features = ["vendored"] }

[profile.release]
lto = true
